### ISSUE TITLE
Workbench Dropdown shrinks Reverse Engineering entry

### ISSUE THREAD

**Issue by neildarlow** [obelisk79/OpenDark#10]
When using OpenDark and opening the Workbench Dropdown, the Reverse Engineering workbench entry is shrunk to make it fit the available width. Perhaps it should be enlarged or dynamically adjusted to the longest entry.

While you are looking at this, the Workbench Dropdown grab-area doesn't have any padding between it and the dropdown like other elements of the theme have.

These are both cosmetic but, I think, worth addressing.

![Screenshot from 2023-10-02 11-01-47](https://github.com/obelisk79/OpenDark/assets/6245505/b6d48de8-29d0-4aa4-8c2b-08b9a28161e2)

**Comment by obelisk79** [comment]
I have fixed this now. I had to target the selector directly and define minimum width to get the full name to show. I'll be looking for a more elegant solution in the future.

![image](https://github.com/obelisk79/OpenDark/assets/17993710/ee498778-b8e0-47d6-a7fc-a8523fcf8de2)
