### ISSUE TITLE
In Combo View/Model, current line is too dark to read unless selected

### ISSUE THREAD

**Issue by drf5n** [obelisk79/OpenDark#14]
This dark-highlighted line in the combo view is hard to read:

<img width="1139" alt="image" src="https://github.com/obelisk79/OpenDark/assets/2236516/2c6b0904-3a38-4eec-8986-358a804aeb09">

I'm not sure where this color is set in the Preferences menu.

**Comment by hasecilu** [comment]
Do you still have the problem? I tried to reproduce but it seems that is the active part now is in white color.

![image](https://github.com/obelisk79/OpenDark/assets/53124818/31b0b73c-7a9e-4215-b53a-7414a37543cf)

**Comment by drf5n** [comment]
I do still have the problem:

<img width="1122" alt="image" src="https://github.com/obelisk79/OpenDark/assets/2236516/65985851-5264-45c0-ba0c-198defa604ce">

<img width="1041" alt="image" src="https://github.com/obelisk79/OpenDark/assets/2236516/414f2d21-09a6-409c-8902-50126170f0a6">

I'm on a Mac, incase that is a difference:

```
[code]
OS: macOS 13.2.1
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Macro_Align_View_to_Face.png
  * startup.py.FCMacro
  * Align_View_to_Face.FCMacro
  * Camera
  * OpenDark 2023.10.9
  * MacroStartup
  * rollCamera.py
  * Macro_MeshToPart.png
  * junk2.FCMacro
  * junk.py
  * test.FCMacro
  * Camera.FCMacro
  * Align_view_to_Line.FCMacro
  * MeshToPart.FCMacro
  * ViewRotation.FCMacro
  * Camera.png
  * 3D_Printing_Tools
[/code]


```

**Comment by obelisk79** [comment]
So far, I have been completely unable to reproduce this behavior on my computer. It makes correcting the issue extremely difficult.

**Comment by drf5n** [comment]
Would you know what settings/parameters control the this text color?  With a name or a file, maybe I could track down what is is going on.

**Comment by drf5n** [comment]
> edit: I suggest you make a copy of your preferences and then reset all of it.

Doesn't `Preferences/General/General/Classic Theme; Apply`, and then maybe a restart, do the resetting?

**Comment by kaktusus** [comment]
https://wiki.freecad.org/Preferences_Editor#Introduction

> Pressing the Reset button in the lower left corner of the Preferences dialog opens a menu ([introduced in version 0.22](https://wiki.freecad.org/Release_notes_0.22)) with options to reset preferences to their default values. You can reset the current tab, the current group, or all preferences.

**Comment by drf5n** [comment]
Oops. this reset:
<img width="876" alt="image" src="https://github.com/obelisk79/OpenDark/assets/2236516/3f41705f-9659-4bc8-aae5-fdfe3a880e3e">

Thanks.  

Here's what I get with a Reset, close and reopen, open the engine block sample part, update OpenDark to 2023.10.22 in ; then  Preferences/General/General/OpenDark,  open the crankase/proeprties and click on Base:

Active line is blue and black on black and dark blue:

![image](https://github.com/obelisk79/OpenDark/assets/2236516/a6695387-398a-4665-8644-6a99f5e91aa8)


About:
[code]
OS: macOS 13.2.1
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Macro_Align_View_to_Face.png
  * startup.py.FCMacro
  * Align_View_to_Face.FCMacro
  * Camera
  * OpenDark 2023.10.22
  * MacroStartup
  * rollCamera.py
  * Macro_MeshToPart.png
  * junk2.FCMacro
  * junk.py
  * test.FCMacro
  * Camera.FCMacro
  * Align_view_to_Line.FCMacro
  * MeshToPart.FCMacro
  * ViewRotation.FCMacro
  * Camera.png
  * 3D_Printing_Tools
[/code]

![image](https://github.com/obelisk79/OpenDark/assets/2236516/2c513183-e495-4ec9-893e-940d820cb0c0)

Maybe it is some Mac difference?

**Comment by kaktusus** [comment]
What you see may also depend on your system's window manager configuration.

**Comment by drf5n** [comment]
Seems like a bit of a bug if the configuration system lets you change the background colors around text with externally controlled colors.

**Comment by obelisk79** [comment]
This is a problem with the stylesheet for certain. I just need to find a way to recreate it before I can correct it.

**Comment by drf5n** [comment]
Can you set the foreground text color in with a stylesheet?  It is unclear (to me) what property sets the foreground text color in the Model/Combo View.

This bit of code looks related to the issue:

https://github.com/FreeCAD/FreeCAD/blob/b70956ba3dd0ffb12bac6761d49dcacb5de8c950/src/Gui/Tree.cpp#L4910-L4919

**Comment by obelisk79** [comment]
I have just pushed an update to the main stylesheet. Can you check to see if this corrected your issue? I'm doing a little bit of blind fishing on this issue.

**Comment by drf5n** [comment]
OK, here's after update, reset and restart with the EngineBlock/CrankCase/Box Carvers clicked on :

<img width="1277" alt="image" src="https://github.com/obelisk79/OpenDark/assets/2236516/8bf3720c-73ea-4f18-afd6-ea420cd7a50a">

And same after applying the updated OpenDark, :

<img width="1113" alt="image" src="https://github.com/obelisk79/OpenDark/assets/2236516/c730aaec-e369-4b57-8ae9-0bc32b5d38c8">

Looks like that corrects the current line darkness.  Cool.  
However the non-active "Crankcase with journals" line could be lightened a little bit above background toward legibility.

Looks like the foreground of the selected line is controlled by QTreeView:selection-color and QTreeView:item:selected:color from:

https://github.com/obelisk79/OpenDark/commit/762492c117995483ea210797a668b820f619d3a8



[code]
OS: macOS 13.2.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34729 (Git)
Build type: Release
Branch: main
Hash: 0b0e9effeb42c9ad441e1a70efcbfb2cd3d05223
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Freecad-Built-in-themes-beta 1.2.2
  * Macro_Align_View_to_Face.png
  * startup.py.FCMacro
  * Align_View_to_Face.FCMacro
  * Camera
  * OpenDark 2023.10.22
  * MacroStartup
  * rollCamera.py
  * Macro_MeshToPart.png
  * junk2.FCMacro
  * junk.py
  * test.FCMacro
  * Camera.FCMacro
  * Align_view_to_Line.FCMacro
  * MeshToPart.FCMacro
  * ViewRotation.FCMacro
  * ExtremeProLight 1.6.0
  * Camera.png
  * 3D_Printing_Tools
[/code]

**Comment by obelisk79** [comment]
I can't seem to make that line go dark like your screenshot. When you say non-active, do you mean you hit the spacebar to hide it? Also, if you're able to modify the stylesheet directly, add this bit of code at the very bottom of OpenDark.qss and let me know if it modifies that specific bit you're seeing the issue with. The colors will be annoying, but this is just a test.

```QTreeView::item:disabled {
    color: #ff00ff;
    background-color: #00ff00;
}

**Comment by drf5n** [comment]
Now it doesn't seem to be blacked out.   Seems OK now. Maybe I didn't reset & reload something properly.

<img width="1000" alt="image" src="https://github.com/obelisk79/OpenDark/assets/2236516/f68e76a5-9dc7-49ee-93e1-13dc286a0cd0">

The lines all seem very readable now.


```
[code]
OS: macOS 13.2.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34729 (Git)
Build type: Release
Branch: main
Hash: 0b0e9effeb42c9ad441e1a70efcbfb2cd3d05223
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Freecad-Built-in-themes-beta 1.2.2
  * Macro_Align_View_to_Face.png
  * startup.py.FCMacro
  * Align_View_to_Face.FCMacro
  * Camera
  * OpenDark 2023.10.22
  * MacroStartup
  * rollCamera.py
  * Macro_MeshToPart.png
  * junk2.FCMacro
  * junk.py
  * test.FCMacro
  * Camera.FCMacro
  * Align_view_to_Line.FCMacro
  * MeshToPart.FCMacro
  * ViewRotation.FCMacro
  * ExtremeProLight 1.6.0
  * Camera.png
  * 3D_Printing_Tools
[/code]

```

**Comment by obelisk79** [comment]
ok, I'll close out this issue then, thanks for reporting back.
