### ISSUE TITLE
yellow or text color in spreadsheet aliased cells needs adjustment

### ISSUE THREAD

**Issue by kinghat** [obelisk79/OpenDark#16]
this color combo in spreadsheets aliased cells is hard to read:

![image](https://github.com/obelisk79/OpenDark/assets/16073360/87b6a0cd-1398-4b19-afbc-31be708117a8)

**Comment by obelisk79** [comment]
Fixed, should be able to update, remember to restart the program afterwards.

**Comment by kinghat** [comment]
for anyone whom comes across this, i had to go into preferences and click apply on the theme and restart to get it to show this fix. ymmv
