### ISSUE TITLE
Checkboxes on transparent task view

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#19]
0.22dev:
Checkboxes in the transparent task box overlay not visible:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/7e4a5718-3f75-400d-b323-cce35d389a62)

**Comment by obelisk79** [comment]
I'll look into this. However it looks like you don't have the opendark overlay stylesheet applied. Can you verify? Also, which task is this screenshot from, something in FEM?

![image](https://github.com/obelisk79/OpenDark/assets/17993710/81dc783e-e43e-4b08-a834-535263b2a3a0)

**Comment by maxwxyz** [comment]
@obelisk79  You are right, overlay style sheet was on auto. I was unaware that I have to setup the theme in another sub menu again. Could this be set in future also by applying the theme?
Its a task screenshot in FEM, in this case _FEM_ConstraintDisplacement_.
When OpenOverlay is applied it looks different but still not ideal:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/ed5529e7-e10b-4924-9f3c-300cec5f2e02)
