### ISSUE TITLE
README screenshot of Preferences doesn't show 'OpenDark' preference pack

### ISSUE THREAD

**Issue by luzpaz** [obelisk79/OpenDark#2]
![image](https://github.com/obelisk79/OpenDark/assets/4140247/7132b817-0c77-458e-8d4c-244182cb6315)

If you look at the 'Preference Pack Name' column there is no mention of OpenDark. This is confusing. What should users expect in the preferences when they install this pref pack?

**Comment by obelisk79** [comment]
I'll replace the screenshot when I am at home later today. This is a leftover from when I started the pack and called it FreeCAD_Dark. Good catch.

**Comment by obelisk79** [comment]
I have updated the picture to reflect what will be seen in the preferences window.
