### ISSUE TITLE
Slider in task view too small

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#20]
0.22dev
Slider in transparent overlay task dialog is too small:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/63c25517-ed94-4a5c-bdb3-2e27836aa774)

**Comment by obelisk79** [comment]
can you share the file for this? I don't use that workbench typically.

**Comment by maxwxyz** [comment]
See here: [femslider.zip](https://github.com/obelisk79/OpenDark/files/13202201/femslider.zip)

![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/d39d8c52-7639-49dd-ac2d-c27c0f58e672)


A good slider is when editing Warp options inside the tree: Analysis>Pipeline_CCX_Results>WarpVector
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/e8a83642-c6b0-4f38-9607-59351084e96e)
