### ISSUE TITLE
Dropdown Background in Task View Overlay White

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#21]
Dopdown in task view overlay (transparency on) is pure white with white font --> unreadable.
PartDesign Revolution Dialog 
0.22dev 2023-10-26
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/19eeeff3-d903-4803-82e1-3113c3668a9f)

**Comment by obelisk79** [comment]
Just to make sure I understand, this only happens with overlay mode, correct?

**Comment by maxwxyz** [comment]
Yes, only in overlay and in transparent as well as not transparent.
