### ISSUE TITLE
Buttons in Task View Transparent Overlay not Recognizable

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#22]
Buttons in the Task View with transparent overlay and OpenDark stylesheet not recognizable as button. It looks just like text.
In this case the Boolean dialog in Part Design "Add body" and "Remove body". Hovering the text will show a slight border of the buttons.
0.22dev 2023-10-26
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/7319fa2d-b780-4165-a592-f69c5809eef8)

**Comment by obelisk79** [comment]
This should be fixed now.

**Comment by maxwxyz** [comment]
No.
Am I using the right version? 
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/809c9c9b-1d09-45cd-ba44-5e088b74412b)

See those buttons. Add and Remove not visible, you can only see the outline when I hover remove:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/c25d76e9-5348-4bcd-a2b9-e4b7e26fdbde)

**Comment by maxwxyz** [comment]
Also this Button is not identifiably as a button: 
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/1da48553-60f6-4cb4-a985-7d0b4ce6a08a)

**Comment by obelisk79** [comment]
Ok, I figured it out. Mild rant, whoever designed this dialog set those buttons up as toolbar buttons instead of as regular pushbuttons so I had to add special styling for task panels. Hopefully there aren't other cascading effects from this.

**Comment by maxwxyz** [comment]
Maybe check with the FEM maintainers to achieve a consistent UI

**Comment by obelisk79** [comment]
It's not just FEM actually. I found the issue in multiple places.
