### ISSUE TITLE
Buttons in overlay top bar too small and dark

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#23]
The buttons in the overlay bar at the top (to change transparency, auto hide, ... are too small to hit and too dark to see the icons: 
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/245c3bc9-eb52-4492-8441-b157c04431f0)

**Comment by tigert** [comment]
Yeah, they are also super tiny

**Comment by obelisk79** [comment]
This should be corrected now.
