### ISSUE TITLE
Error popup is white-on-white

### ISSUE THREAD

**Issue by drf5n** [obelisk79/OpenDark#24]
If you cause an error, the popup window has the light grey text on a white background.

See the bottom of this image:

<img width="857" alt="image" src="https://github.com/obelisk79/OpenDark/assets/2236516/d5f9c690-56cb-4701-abc2-27b899cee9f0">

In this case I revolved a sketch that straddled an axis to cause the error.  In Report View the error was "14:17:38  Revolution: Revolve axis intersects the sketch"

[bushing.FCStd.gz](https://github.com/obelisk79/OpenDark/files/13198869/bushing.FCStd.gz)

```
OS: macOS 13.2.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34729 (Git)
Build type: Release
Branch: main
Hash: 0b0e9effeb42c9ad441e1a70efcbfb2cd3d05223
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Freecad-Built-in-themes-beta 1.2.2
  * Macro_Align_View_to_Face.png
  * startup.py.FCMacro
  * Align_View_to_Face.FCMacro
  * Camera
  * OpenDark 2023.10.22
  * MacroStartup
  * rollCamera.py
  * Macro_MeshToPart.png
  * junk2.FCMacro
  * junk.py
  * test.FCMacro
  * Camera.FCMacro
  * Align_view_to_Line.FCMacro
  * MeshToPart.FCMacro
  * ViewRotation.FCMacro
  * ExtremeProLight 1.6.0
  * Camera.png
  * 3D_Printing_Tools
```

**Comment by obelisk79** [comment]
So, I find this report interesting for a few reasons.

1. Digging around FreeCAD's code, I can't find an obvious widget to target by name for this.
2. I can't seem to figure out how to directly target this (see #1)
3. If I change from opendark to the dracula stylesheet it changes from black to white background.

With opendark enabled, I see a black background for this widget, so the fact that you're getting something else entirely is interesting to say the least.

**Comment by drf5n** [comment]
Yes.  Since Freecad/QT uses stylesheets, there seems to be a lot of cascading levels of settings that change the defaults up the cascade.  It's too bad there doesn't seem to be QT inspector thing that lets you highlight bits of the UI and show you the CSS hierarchy as shown in a browser inspector.

**Comment by drf5n** [comment]
A quicker test case is this console code:

```
FreeCAD.Console.PrintError("Hello world FreeCAD.Console.PrintError\n")
```

<img width="897" alt="image" src="https://github.com/obelisk79/OpenDark/assets/2236516/f9d08b8c-f2dd-4bc0-b6dc-2badd4e5012e">

**Comment by obelisk79** [comment]
resovled using 

```
Gui--NotificationLabel {
}
```

**Comment by drf5n** [comment]
Works for me:

<img width="906" alt="image" src="https://github.com/obelisk79/OpenDark/assets/2236516/3a24c6ae-1c23-4b47-8a1c-423cabd4767e">

Thanks
