### ISSUE TITLE
FEM Task Overlay: Selected Faces not Expandable or Scrollable

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#27]
In some task views (in tzhis case FEM>Analysis feature parameters) the selected items are cut in half. There is no way to expand that field and only the first item is visible. No scrollbar visible.

![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/58736b33-f471-469b-a99e-4e95c397afc6)

**Comment by obelisk79** [comment]
These things look ok for me here, I am about to push a PR, I suppose update OpenDark and confirm if this issue is still present.

**Comment by obelisk79** [comment]
Same thing as before, I can't reproduce this one. If you come across it again please let me know.

**Comment by maxwxyz** [comment]
![image](https://github.com/obelisk79/OpenDark/assets/6246609/a86f6764-f933-4878-998b-adf973866589)
yes its good now!
