### ISSUE TITLE
TechDraw Edit Dimension Dialog Overlay Task View

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#28]
The dialog to edit a dimension (and maybe other) in TechDraw WB has a poor contrast and the two tolerance fields are clipped:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/2982ca67-1dcf-40cc-a2d5-acd0b3c9baa4)

**Comment by obelisk79** [comment]
This should be fixed with tonight's pr.
