### ISSUE TITLE
Some Errors in Part WB Task Overlays 

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#30]
Part WB in this case the fillet tool.

- radio buttons cut off at the bottom
- vertical slider too small (like the horizontal in FEM you have already fixed)
- checkboxes poorly distinguishable from the background
- 
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/41a77577-ac43-4630-b10d-fee9716bff69)

**Comment by maxwxyz** [comment]
Checkboxes also cut off in line attributes dialog of TechDraw:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/e04647e5-88a4-4e42-a4ef-375781b9834c)

**Comment by maxwxyz** [comment]
Radio box in general cut off, also in preferences dialog

**Comment by obelisk79** [comment]
All of these issues should now be corrected.
