### ISSUE TITLE
Transform dialog: text boxes touch each other

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#31]
The transform dialog with touching textboxes:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/b057a87a-dbd3-4047-b4df-a91e5a591624)

**Comment by obelisk79** [comment]
I've resolved this
![image](https://github.com/obelisk79/OpenDark/assets/17993710/b5de523e-8818-46b7-a415-35fe1ba4e197)
