### ISSUE TITLE
Spreadsheet: Text no visible on autocompletion while typing

### ISSUE THREAD

**Issue by hasecilu** [obelisk79/OpenDark#36]
Right click on a spreadsheet cell, select `Configuration table`
In the `Property` (2nd) form you choose the element to which the configuration table will be applied.
When you type the name, the autocompletion appears, in this case is a single entry that is cropped.

![image](https://github.com/obelisk79/OpenDark/assets/53124818/6024725f-362a-43aa-b88b-cd28d284bde2)

Same in Formula editor
![image](https://github.com/obelisk79/OpenDark/assets/53124818/6c0365b2-2ed1-4309-a9a3-39a397438d2a)

**Comment by kinghat** [comment]
i think this is for anywhere you use auto complete:

![image](https://github.com/obelisk79/OpenDark/assets/16073360/814f6a33-322c-44f7-b9df-708520ee03c4)

here is how it looks normally(dark theme):

![image](https://github.com/obelisk79/OpenDark/assets/16073360/be8dc90e-1e63-4cd5-a68d-64b4bea891d0)
