### ISSUE TITLE
Part Design: Pad dialog indentations

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#37]
In the pad dialog the direction section is indented, is this wanted? The text above and below are in line (checkboxes and also on the right side):
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/2366a896-b755-4c37-8e40-668f6e7aa706)

**Comment by maxwxyz** [comment]
Same in pocket dialog.

**Comment by obelisk79** [comment]
This is related to how the task panels nest widgets and groups and cannot be resolved via stylesheet as far as I'm aware. 

If you know of a stylesheet which has everything aligned I can check and compare code. Otherwise I'm closing this as unresolvable.
