### ISSUE TITLE
Preferences: TechDraw Dropdowns too large

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#39]
Some dropdowns in the preferences dialog under the TechDraw WB are too big:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/e9730f64-4a14-41a7-81eb-895054fced76)

**Comment by obelisk79** [comment]
I bet those are menu buttons instead of qcombobox widgets. I'll look into it

**Comment by obelisk79** [comment]
I'm not 100% happy with the result, but I believe I've corrected this close to where it should be pretty unnoticeable.
