### ISSUE TITLE
License confict. You link to LGPLv3 but the LICENCE file in this repo is MIT.

### ISSUE THREAD

**Issue by luzpaz** [obelisk79/OpenDark#4]
License confict. You link to LGPLv3 but the LICENCE file in this repo is MIT.

_Originally posted by @luzpaz in https://github.com/obelisk79/OpenDark/issues/3#issuecomment-1737962901_

**Comment by obelisk79** [comment]
I'm quite new to github and this process, thanks for your diligence and patience. I've updated the selected license and file document.
