### ISSUE TITLE
preferences more tabs arrow icons

### ISSUE THREAD

**Issue by kinghat** [obelisk79/OpenDark#41]
something is off with the more tabs arrow icons in preferences(draft):

![image](https://github.com/obelisk79/OpenDark/assets/16073360/7c52435e-5d40-4a94-a27b-482985a5ba6a)

**Comment by obelisk79** [comment]
I have managed to increase the width of these buttons using the 
QTabBar::scroller subcontrol, although they are still difficult to distinguish. I'll have to dig a little deeper into this before I'll call it completed.

**Comment by obelisk79** [comment]
Ok, I've managed to target the buttons and add a contrasting border to them so they are appropriately viewable. PR to follow.

**Comment by hasecilu** [comment]
Also happens when you have a lot of files open and you are working on one the firstly open.

![image](https://github.com/obelisk79/OpenDark/assets/53124818/412a4afc-fb5d-40f5-8c93-59b186f946ac)
