### ISSUE TITLE
tree view rename text box cuts off low characters

### ISSUE THREAD

**Issue by kinghat** [obelisk79/OpenDark#42]
low characters are cut off when renaming objects in the tree view:

![image](https://github.com/obelisk79/OpenDark/assets/16073360/4e258fd1-87be-4f21-bc37-3290c63b101b)

![image](https://github.com/obelisk79/OpenDark/assets/16073360/0639151c-472d-47f4-9712-6d171832e2b6)

**Comment by obelisk79** [comment]
I have fixed this locally, PR to follow soon.
