### ISSUE TITLE
draft workbench snap icons are unusable

### ISSUE THREAD

**Issue by kinghat** [obelisk79/OpenDark#43]
you can see that not of the snap icons function in the draft workbench:

https://github.com/obelisk79/OpenDark/assets/16073360/0fdb7167-945e-4960-9051-26fb8434d14e

they function properly in dark theme:

![image](https://github.com/obelisk79/OpenDark/assets/16073360/50fe953e-b67f-407f-b5b3-c7d06ddb384c)

> OS: KDE Flatpak runtime (KDE/plasma)
> Word size of FreeCAD: 64-bit
> Version: 0.21.2.33771 (Git)
> Build type: Release
> Branch: (HEAD detached at b9bfa5c)
> Hash: b9bfa5c5507506e4515816414cd27f4851d00489
> Python 3.10.13, Qt 5.15.10, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
> Locale: English/United States (en_US)
> Installed mods: 
>   * BIM 2021.12.0
>   * ThreadProfile 1.89.0
>   * fasteners 0.4.70
>   * ExtremeProDark 2.9.0
>   * Manipulator 1.5.0
>   * OpenDark 2023.10.30

**Comment by obelisk79** [comment]
I have a working fix for this issue. PR to follow soon.
