### ISSUE TITLE
Task dialog icon only toolbuttons are too wide

### ISSUE THREAD

**Issue by adrianinsaval** [obelisk79/OpenDark#45]
I've seen it first on sketcher:
![Screenshot_20231104_205108](https://github.com/obelisk79/OpenDark/assets/36372335/76c16c83-5384-49d3-ae36-0af29cada0c8)
previously reported on the forum: https://forum.freecad.org/viewtopic.php?p=717040#p717040

this one might be the same issue too: https://forum.freecad.org/viewtopic.php?p=721896#p721896
![Scr_20231129_092141](https://github.com/obelisk79/OpenDark/assets/36372335/52e7704c-06d7-4520-95d2-f76b94e25abb)

**Comment by obelisk79** [comment]
Saw your comment on the forum also. I'd like to maintain some kind of general consistent button width because things were highly inconsistent previously. I'll have to see if I can target icon-only buttons like this in the stylesheet.

**Comment by obelisk79** [comment]
I have this fixed for the next release.

**Comment by adrianinsaval** [comment]
do you mean in opentheme?

**Comment by obelisk79** [comment]
> do you mean in opentheme?

I will still update this repo directly for a short time, but everything will be combined in OpenTheme in the long term.
