### ISSUE TITLE
Can not resize windows in tile view

### ISSUE THREAD

**Issue by vancampbeans** [obelisk79/OpenDark#46]
See screenshots. I can resize the windows in tile view without problem if I switch back to the standard FreeCAD theme. The mouse does not change shape to the re-sizing arrows when I hover over the border between the tiles and I can not drag to change the tile size.
Using Debian 12 with i3wm.
Edit: Using FreeCAD v0.21.1 r33694

![Screenshot_2023-12-03_22-12-49](https://github.com/obelisk79/OpenDark/assets/133628560/b3c5e11a-0a0a-4168-ab02-54c68bb9437c)
![Screenshot_2023-12-03_22-13-18](https://github.com/obelisk79/OpenDark/assets/133628560/386e6a03-bfce-4a92-bc4d-0a15f130c2de)

Edit2: Below screenshot with tile sizes adjusted in the classic (no style sheet) theme.
![11Screenshot_2023-12-03_22-18-04](https://github.com/obelisk79/OpenDark/assets/133628560/48831917-649f-4460-babe-bcbfe8eb6a78)

**Comment by hasecilu** [comment]
I can confirm on Arch Linux Openbox Version: 0.21.2.33771 (Git)

**Comment by obelisk79** [comment]
I have this resolved within the stylesheet framework now. It should be reflected in the next update. Thank you for the report.
