### ISSUE TITLE
Dark link colors in Property table

### ISSUE THREAD

**Issue by brandonbeaumia** [obelisk79/OpenDark#5]
![unnamed](https://github.com/obelisk79/OpenDark/assets/650565/6bad70a7-a717-49fe-a363-c118f3005d46)
This is what it looks like on Windows, but on my Pop_OS desktop the blue is a nicer muted blue. Either way, should probably be defined for consistency.

I implemented a fix for this in the Dracula theme using the [haslink] feature:

```
QLabel[haslink="true"] { /* applies to all links (See Help->About), but most importantly in PropertyEditor. Trying to specify PropertyEditor fails.*/
    color: #8be9fd;
}
```

By the way, I'm *very* excited to see a theme that isn't built off the same old template! For a fresh start you've done an incredible job already.

**Comment by obelisk79** [comment]
I've corrected this color, your solution was quite helpful, thanks! I'll pull an update later tonight.
