### ISSUE TITLE
Using Overlay, view buttons are too small

### ISSUE THREAD

**Issue by PaddleStroke** [obelisk79/OpenDark#52]
Using overlay, the view icons are too small to use : 
![image](https://github.com/obelisk79/OpenDark/assets/19984177/f23e812a-3245-4e6c-b0f1-14faed42c9e0)
(3800*1600 screen on windows with 125% scaling fiy)

**Comment by hasecilu** [comment]
It seems a problem with high density display. It looked like that more than one month ago on 1920x1080 screen but was fixed.
![image](https://github.com/obelisk79/OpenDark/assets/53124818/63ec520a-87f0-40cc-ab9f-b9eb3c85b5c2)

**Comment by obelisk79** [comment]
@PaddleStroke I'm unable to recreate this. When I set my system (Linux with Plasma desktop) to a scaling of 125% they get even bigger, and with no dpi scaling at 1440p the size is fine. I'm not sure the theme can address this, unless you are used to this not happening with other themes (not classic).

I'm going to close this as unplanned for now. I'll reopen if I get more information that indicates this is an issue with the theme and not just bad scaling on behalf of FreeCAD or Qt.

**Comment by PaddleStroke** [comment]
The screenshot from @hasecilu is when the tree overlay is active. In this case it looks OK.
The issue is when the tree is NOT overlay. Then the buttons are small and almost the same color as the background.

**Comment by obelisk79** [comment]
That's for the explanation. I'll reopen and investigate.

**Comment by obelisk79** [comment]
I've isolated the problem and have a fix, things 'should' be good to go now. Those buttons are tied to global QToolButton properties so I had to isolate them via stylesheet and set margin to 1px. Will be fixed in next release.
