### ISSUE TITLE
Sketcher: Task dialog lists of elements and constraints use different designs

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#54]
In the Sketcher task dialog there are two lists for constraints and elements.
These display each a different item height and a different checkbox design.
When selecting geometry or constraints from the 3d view, the selected items are highlighted in a different color (white/blue). When selecting the items from the task dialog list, both are highlighted in blue.
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/92e72cc1-9255-4a4b-afb2-a325bc3af92f)

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35449 (Git)
Build type: Release
Branch: main
Hash: f3fa2ba9c9b1999e5c32d3ae544481b6e17553bb
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.24.9
  * CurvedShapes 1.0.5
  * Curves 0.6.19
  * Defeaturing 1.2.1
  * fasteners 0.4.75
  * FEMbyGEN 2.0.0
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.3.13
  * woodworking 0.21.1.33694
```

**Comment by obelisk79** [comment]
This was an issue within FreeCAD's code. 
Corrected with this PR I believe: https://github.com/FreeCAD/FreeCAD/pull/12054

I'm going to close for now. I will reopen it if it turns out there are still consistency issues related to the theme.
