### ISSUE TITLE
[Problem] Base planes show as blue, 100% filled

### ISSUE THREAD

**Issue by YosypC** [obelisk79/OpenDark#57]
![image](https://github.com/FreeCAD/FreeCAD/assets/50027752/cc55e369-72f6-417f-8b23-0e8fbed2a05b)

No issues without the theme disabled.

```
OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35315 (Git) AppImage
Build type: Release
Branch: main
Hash: 09f67f2f6bff1c57ac8019a5ba2f4a2c41025ee6
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.1
```

**Comment by obelisk79** [comment]
That is very strange, no one else has reported such an issue. I'm not even sure where to begin to narrow this down. Have you tried/compared to other themes? Dracula, ProDark?

**Comment by YosypC** [comment]
I have experienced this exact problem in the past months ago, unfortunately I can't gather the version.
I have applied the theme back, and it shows no more.

Shall we close this then?
````
OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35315 (Git) AppImage
Build type: Release
Branch: main
Hash: 09f67f2f6bff1c57ac8019a5ba2f4a2c41025ee6
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.17

**Comment by obelisk79** [comment]
Yes, considering that I've never heard of this problem before, I am left to assume it is a software glitch and not directly related to the theme. Thanks for the report though. I'm going to close this for now. If you are able to isolate the problem to OpenDark and can provide me with a way to consistently reproduce it let me know and I'll gladly look into it.

**Comment by YosypC** [comment]
After reading your message I remembered that almost certainly it's not this theme's problem. I recall having had this problem many months, if not years ago on vanilla FC, before I even knew the theme. That's why you have no clue where to begin from.
