### ISSUE TITLE
Sketcher: External Geometry barely visible

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#58]
In Sketcher WB the external geometry line style and color is barely visible as its rendered on top of the external lines:
![image](https://github.com/obelisk79/OpenDark/assets/6246609/d692c0de-4447-4fd2-a25a-e81a1ab427cd)

**Comment by obelisk79** [comment]
So, would you say this is a patter, color, or rendering issue? Contrast with the geometry displayed underneath will always be poor particularly when the 3d geometry is such a light color compared to the dark background. I am open to suggestions on color/pattern, using this palette: https://yeun.github.io/open-color/

The specific color and pattern setting is in Preferences > Sketcher > Appearance
