### ISSUE TITLE
Text of coordinate system in the 3D view too dark

### ISSUE THREAD

**Issue by Be-Cool-Man** [obelisk79/OpenDark#61]
The text from the coordinate system in the 3D view is too dark:
![Coordinate System](https://github.com/obelisk79/OpenDark/assets/7967418/b27383d0-6fb2-4999-b2f5-86f323f555bf)

**Comment by obelisk79** [comment]
Hello, thanks for the report. Unfortunately this text is not currently able to be customized. There is a pull request on FreeCAD to change that. I'll update once it gets merged.

**Comment by Be-Cool-Man** [comment]
I've just found out, that you can change the color oft the text from the coordinate system In 0.22.0dev:
 
Edit ⇒ Preferences… ⇒ Display ⇒ 3D View ⇒ General ⇒ Letter color
