### ISSUE TITLE
AddonManager: Dropdown checkboxes huge and not aligned

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenDark#68]
Not sure if fixable with a theme but the dropdown menu in the addon manager has huge checkmarks and boxes and they are not vertically centered / alignes which becomes visible when hovering the entries:
![image](https://github.com/obelisk79/OpenDark/assets/6246609/86125f95-0e5a-4586-b3ef-f5921cfe8ef9)

**Comment by maxwxyz** [comment]
same in open light: 
![image](https://github.com/obelisk79/OpenDark/assets/6246609/35d69039-ee4e-49f4-ab72-5a2546c7d2a2)

**Comment by obelisk79** [comment]
@maxwxyz open this as an issue under the open themes repo. I'm going to eventually delete this repo in a few weeks most likely and treat it as deprecated.

**Comment by maxwxyz** [comment]
will do, but you can also transfer all issues between the repos

**Comment by obelisk79** [comment]
I was not aware of that. Also I'm not sure which are still valid, I think several may have been addressed but I didn't document it during the refactor. I'll spend some time validating before moving them over.

**Comment by maxwxyz** [comment]
I'll close this as I've added it manually to OpenTheme: https://github.com/obelisk79/OpenTheme/issues/2
