### ISSUE TITLE
Tiny "more / expand" button in toolbars

### ISSUE THREAD

**Issue by brandonbeaumia** [obelisk79/OpenDark#7]
For toolbar buttons that don't fit, a small button expands a box to show the others. Here you can see me hovering over it: the tiny blue vertical strip.

![unnamed2](https://github.com/obelisk79/OpenDark/assets/650565/0ebb3f93-aeda-40aa-a1c2-5a6f6882fd4f)

This is styled in Dracula like so:

```
/*The "show more" button  (it can also be stylable with "QToolBarExtension" */
QToolBar QToolButton#qt_toolbar_ext_button {
    margin: 1px;
    padding: 0px;
    padding-left:1px;
    padding-right:1px;
    qproperty-icon: url(qss:images_dark-light/right_arrow_light.svg);
    image: transparent;
    background-repeat: none;
    background-position: center left;
}

QToolBar QToolButton#qt_toolbar_ext_button:hover {
    qproperty-icon: url(qss:images_dark-light/right_arrow_lighter.svg);
    border-color: #1b1c24;
    background-color: rgba(255,255,255,20)}

QToolBar QToolButton#qt_toolbar_ext_button:on {
    qproperty-icon: url(qss:images_dark-light/right_arrow_lighter.svg);
    border-color: #1b1c24;
    background-color: #6272a4;
}
```

Some of this might be superfluous if you'd like to work on slimming it down, but this particular collection of margin/padding settings seemed to be the only way to make the button large enough to really use.

**Comment by obelisk79** [comment]
Ok, this one is quite frustrating... 
this looks ok until mouse-over
![image](https://github.com/obelisk79/OpenDark/assets/17993710/e16a2a92-e3e9-464b-9904-b4c7f51c3d16)

![image](https://github.com/obelisk79/OpenDark/assets/17993710/4e7f401e-0dba-4bd7-aa51-4c842d2de07a)

**Comment by obelisk79** [comment]
Here is what I've come up with so far
```
QToolBarExtension {
    border: 0px;
    min-width: 10px;
    background-color: transparent;
    qproperty-icon: url(qss:images_dark-light/right_arrow_light.svg);
    &:hover {
        border: 0px;
    }
    &:selected {
        background-color: transparent;
    }
}
```

**Comment by brandonbeaumia** [comment]
What do you think of this?
Regular:
![image](https://github.com/obelisk79/OpenDark/assets/650565/5ab4eb12-f92e-4f18-979e-de295a4a1a1e)

Hover:
![image](https://github.com/obelisk79/OpenDark/assets/650565/d6ffa599-e6b3-49fe-bf12-4b7f5d5d19db)

Selected:
![image](https://github.com/obelisk79/OpenDark/assets/650565/6a1408d2-1dc8-4a7e-a2c1-1d22bf857654)

I think I achieved what you were going for in your first response by fiddling around some more and adding JUST enough margin/padding to the toolbars themselves:
```
QToolBar {
  margin:4px; /*Exactly enough room to fit the QToolBarExtension (margin+padding+border of QToolBarExtension)*/
}

QToolBarExtension {
  min-width:10px;
  margin: 0px; /* Resetting margin required to prevent overlap with next toolbar */
  padding: 1px 0px 0px 3px; /* Compensate for extra white space on in arrow SVG */
  border: 1px solid transparent; /* Must include a transparent border, or adding one later (hover etc) will change the icon size.*/
  background-color: transparent;
  qproperty-icon: url(qss:images_dark-light/right_arrow_light.svg);
  background-position:center;
}

QToolBarExtension:hover {
  border:1px solid #264b69;
  qproperty-icon: url(qss:images_dark-light/right_arrow_lighter.svg);
}

QToolBarExtension:selected,
QToolBarExtension:on {
  border:1px solid #264b69;
  background-color: #264b69;
  qproperty-icon: url(qss:images_dark-light/right_arrow_lighter.svg);
}
```

Try this and see if you still get that strange overlap?

**Comment by obelisk79** [comment]
Thanks for the insight, it helped. However I'm still not 100% happy with how I had to make this work. I really wanted to avoid adding in vertical margins.

Here's the code I came up with:
```
QToolBar {
    background-color: transparent;
    margin-top: 8px;
    padding: 1px;
    border-bottom: 1px solid $softborder;
}

QToolBarExtension {
    border: 1px solid transparent;
    min-width: 16px;
    background-color: transparent;
    qproperty-icon: url(qss:images_dark-light/light_expand.svg);
}

QToolButton {
    margin: 0px 4px 0px 4px;
    padding: 0px;
    &:hover {
        border: 1px solid $accent-border;
    }
    &:focus {
        border: 1px solid $accent-border;
    }
    &:pressed {
        border: 1px solid $accent-border;
        background-color: $accent-bg;
    }
    &::menu-button {
        @include noborder;
        padding-right: 2px;
        padding-top: -15%;
        width: 12px;
    }
}
```

The result:
![image](https://github.com/obelisk79/OpenDark/assets/17993710/92f6a611-9737-47d0-9b5b-6437e53ec939)

I'm going to close this issue as resolved for now since its functional.

**Comment by brandonbeaumia** [comment]
Yes, the behavior of this is one is pretty weird! Glad you got it though, and I like the look.
