### ISSUE TITLE
addon manager: stop refresh icon regression

### ISSUE THREAD

**Issue by kinghat** [obelisk79/OpenDark#71]
there might have been recent merges that broke the stop refresh icon:

![image](https://github.com/obelisk79/OpenDark/assets/16073360/faea7132-b6c2-464a-a31e-9b3bdb8e4a37)

```
OS: Fedora Linux 39 (KDE Plasma) (KDE/plasma)
Word size of Ondsel: 64-bit
Version: 2024.2.0dev.36135 (Git) AppImage
Build type: Release
Branch: flavor
Hash: 5d3a33067a8c5073b468df07383ffa5028d1c065
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.17
  * Ondsel-Lens 2024.1.22.01
```

**Comment by maxwxyz** [comment]
@kinghat please open a PR in FreeCAD main, this is not related to the theme.

**Comment by kinghat** [comment]
> @kinghat please open a PR in FreeCAD main, this is not related to the theme.

https://github.com/FreeCAD/FreeCAD/issues/13563
