### ISSUE TITLE
Ill-defined table areas in some contexts

### ISSUE THREAD

**Issue by brandonbeaumia** [obelisk79/OpenDark#8]
Where some tables exist on the same-colored background, it looks like part of the interface is just missing (especially the keyboard preferences)

![3](https://github.com/obelisk79/OpenDark/assets/650565/7c316df5-dab4-40ad-ab47-a5a67434625e)
![4](https://github.com/obelisk79/OpenDark/assets/650565/f091429b-66e8-4df6-985c-6af1b1bdc183)

**Comment by obelisk79** [comment]
Yeah, these are problematic because they don't inherit definitions from other parts of the stylesheet like they probably should. I'm working on these now.

**Comment by obelisk79** [comment]
I've fixed this. Just targeted it using 

```
QDialog QTreeWidget {
}

![image](https://github.com/obelisk79/OpenDark/assets/17993710/f22ce1b1-4a72-46cf-aaae-35914c3e9b6c)

```
