### ISSUE TITLE
No indication that menubar items are actually checkboxes

### ISSUE THREAD

**Issue by brandonbeaumia** [obelisk79/OpenDark#9]
![54](https://github.com/obelisk79/OpenDark/assets/650565/799bb65d-0ea8-4b3b-a749-24d539ec293b)

Fixed in Dracula here: https://github.com/dracula/freecad/pull/27/commits/9da77117ad7ea86d637ba2685db13239cd189db5

which added a border around the checkbox icons.

**Comment by obelisk79** [comment]
Thanks for the help!

It's corrected now:
![image](https://github.com/obelisk79/OpenDark/assets/17993710/d3aeaf0e-fcbd-4042-9bfc-d596d495daca)
